login_app/urls.py
from django.urls import path
from . import views

app_name = 'login_app'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('request_password_reset', views.request_password_reset, name='request_password_reset'),
    path('password_reset/', views.password_reset, name='password_reset'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('delete_account/', views.delete_account, name='delete_account'),
]

todo_app/urls.py
# from django.contrib import admin
from django.urls import path

from . import views

app_name = 'todo_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('change_status', views.change_status, name='change_status'),
    path('completed_todos/', views.completed_todos, name='completed_todos'),
    path('delete_todo/', views.delete_todo, name='delete_todo'),
]

todo_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo_app.urls')),
    path('accounts/', include('login_app.urls')),
]

login_app/models.py
from django.db import models
from django.contrib.auth.models import User
from secrets import token_urlsafe


class PasswordResetRequest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    token = models.CharField(max_length=43, default=token_urlsafe, db_index=True, unique=True)
    created_timestamp = models.DateTimeField(auto_now_add=True)  # is never changed
    updated_timestamp = models.DateTimeField(auto_now=True)  # should be updated

    def __str__(self):
        return f'{self.user} - {self.created_timestamp} - {self.updated_timestamp} - {self.token}'

todo_app/models.py
from django.contrib.auth.models import User
from django.db import models


class Todo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    status = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user} - {self.pk} - {self.text} - {self.status}"

login_app/views.py
from django.shortcuts import render, reverse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as dj_login, logout as dj_logout
from django.http import HttpResponseRedirect
from .models import PasswordResetRequest
from django.contrib.auth.decorators import login_required


def login(request):
    user = request.user.is_authenticated
    context = {
        'user': user
    }
    if request.method == 'POST':
        currentUser = authenticate(
            request,
            username=request.POST['user'],
            password=request.POST['password'],
        )
        if currentUser:
            dj_login(request, currentUser)
            return HttpResponseRedirect(reverse('todo_app:index'))
        else:
            context['error'] = 'bad username or password'

    return render(request, 'login_app/login.html', context)


def logout(request):
    dj_logout(request)
    return render(request, 'login_app/login.html')


def request_password_reset(request):
    if request.method == 'POST':
        if username := request.POST.get('username'):
            user = User.objects.get(username=username)
            prr = PasswordResetRequest()
            # TODO: Handle user not found
            prr.user = user
            prr.save()
            print(prr)
            return HttpResponseRedirect(reverse('login_app:password_reset'))
        # TODO: User email provided, not username
    return render(request, 'login_app/request_password_reset.html')


def password_reset(request):
    if request.method == 'POST':
        if token := request.POST.get('token'):
            # TODO: what if the token does not exist
            prr = PasswordResetRequest.objects.get(token=token)
            if request.POST.get('password') == request.POST.get('confirm_password'):
                user = prr.user
                user.set_password(request.POST.get('password'))
                user.save()
                return HttpResponseRedirect(reverse('login_app:login'))
    return render(request, 'login_app/password_reset.html')


def sign_up(request):
    context = {}
    if request.method == 'POST':
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        user_name = request.POST['user']
        email = request.POST['email']
        if password == confirm_password:
            if User.objects.create_user(user_name, email, password):
                return HttpResponseRedirect(reverse('login_app:login'))
            else:
                context = {
                    'error': 'Could not create user account - please try again'
                }
        else:
            context = {
                'error': 'Passwords did not match. Please try again'
            }
    return render(request, 'login_app/sign_up.html', context)


@login_required
def delete_account(request):
    if request.method == 'POST':
        if request.POST['confirm_deletion'] == 'DELETE':
            user = authenticate(
                request, username=request.user.username, password=request.POST['password'])
            if user:
                print(f"Deleting user {user}")
                user.delete()
                return HttpResponseRedirect(reverse('login_app:login'))
            else:
                print("fail delete")

    return render(request, 'login_app/delete_account.html')

todo_app/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Todo
from django.contrib.auth.decorators import login_required


def index(request):
    todos = []
    user = request.user.is_authenticated
    userName = request.user
    if user:
        todos = Todo.objects.filter(user=request.user, status=False)

    if request.method == 'POST':
        text = request.POST['text']
        todo = Todo()
        todo.text = text
        todo.user = request.user
        todo.save()
        todos = Todo.objects.filter(user=request.user, status=False)

    context = {
        'todos': todos,
        'user': user,
        'userName': userName
    }
    return render(request, 'todo_app/index.html', context)


@login_required
def change_status(request):
    pk = request.POST['pk']
    todo = get_object_or_404(Todo, pk=pk)
    if 'checked' in request.POST:
        todo.status = True
    else:
        todo.status = False
    todo.save()
    if 'completed_todos' in request.META['HTTP_REFERER']:
        return HttpResponseRedirect(reverse('todo_app:completed_todos'))
    else:
        return HttpResponseRedirect(reverse('todo_app:index'))


@login_required
def completed_todos(request):
    todos = Todo.objects.filter(user=request.user, status=True)
    context = {
        'todos': todos,
    }
    return render(request, 'todo_app/completed_todos.html', context)


@login_required
def delete_todo(request):
    print(request.META['HTTP_REFERER'])
    pk = request.POST['pk']
    todo = get_object_or_404(Todo, pk=pk)
    todo.delete()
    if request.META['HTTP_REFERER'].split('/')[-2] == 'todo':
        return HttpResponseRedirect(reverse('todo_app:index'))
    else:
        return HttpResponseRedirect(reverse('todo_app:completed_todos'))

login_app/templates/login_app/delete_account.html
{% extends 'base.html' %}
{% block main %}
<h1>Delete Account</h1>
<hr />
<form action="{% url 'login_app:delete_account'%}" method="post">
	{% csrf_token %}
	<div class="form-group">
		<label for="password">Password</label>
		<input name="password" type="password" class="form-control" id="todo" aria-describedby="password"
			placeholder="Enter your password" />
	</div>

	<div class="form-group">
		<label for="delete">Confirmation</label>
		<input name="confirm_deletion" type="text" class="form-control" id="todo" aria-describedby="delete"
			placeholder="DELETE" />
		<small id="deleteHelp" class="form-text text-muted">Type the word: DELETE </small>

	</div>
	<button class="btn btn-danger">Submit</button>
</form>
{% endblock %}

login_app/templates/login_app/login.html
{% extends 'base.html' %}
{% block main %}
<h1>Login</h1>

<form action="{% url 'login_app:login' %}" method="post">
	{% csrf_token %}
	<div class="form-group">
		<label for="username">Username</label>
		<input type="text" class="form-control" id="username" aria-describedby="usernamehelp"
			placeholder="Enter username" name="user" />
		<small id="usernamehelp" class="form-text text-muted">Your username is always protected with us</small>
	</div>

	<div class="form-group">
		<label for="exampleInputPassword1">Password</label>
		<input type="password" class="form-control" id="exampleInputPassword1" placeholder="Enter password"
			name="password" />
	</div>
	<button type="submit" class="btn btn-primary">Submit</button>
</form>
<div class="mt-3">
	<a class="mr-1" href="{% url 'login_app:sign_up' %}">Sign Up</a>
	<span>|</span>
	<a href="{% url 'login_app:request_password_reset' %}">Reset Password</a>
</div>
<hr />
{% if error %}
{{ error }}
{% endif %}
{% endblock %}

<!DOCTYPE html>

login_app/templates/login_app/password_reset.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<meta name="description" content="reset password" />
	<meta name="keywords" content="reset password" />
	<title>Password Reset</title>
</head>

<body>
	<h1>Password Reset</h1>
	<a href="{% url 'login_app:sign_up' %}">Sign Up</a>
	<a href="{% url 'login_app:request_password_reset' %}">Reset Password</a>
	<hr />
	<form action="{% url 'login_app:password_reset' %}" method="post">
		{% csrf_token %}
		<input type="text" name="username" placeholder="User Name" />
		<input type="password" name="password" placeholder="Password" />

		<input type="password" name="confirm_password" placeholder="Confirm password" />

		<input type="text" name="token" placeholder="Token" />
		<button>Submit</button>
	</form>
	<hr />
	{% if error %}
	{{ error }}
	{% endif %}
</body>

</html>

login_app/templates/login_app/request_password_reset.html
{% extends 'base.html' %}
{% block main %}
<h1>Password Reset</h1>
<hr />
<form action="{% url 'login_app:request_password_reset' %}" method="post">
	{% csrf_token %}
	<div class="form-group">
		<label for="username">Username</label>
		<input name="username" type="text" class="form-control" id="username" aria-describedby="username"
			placeholder="Enter username" />
	</div>

	<div class="form-group">
		<label for="email">Email</label>
		<input name="email" type="email" class="form-control" id="email" aria-describedby="email"
			placeholder="Enter email" />
		<button class="btn btn-primary mt-3">Reset Password</button>
	</div>
</form>
<hr />
{% if error %}
{{ error }}
{% endif %}
{% endblock %}

login_app/templates/login_app/sign_up.html
{% extends 'base.html' %}
{% block main %}
<h1>Sign Up</h1>
<hr />

<form action="{% url 'login_app:sign_up' %}" method="post">
	{% csrf_token %}

	<div class="form-group">
		<label for="user">Username</label>
		<input name="user" type="text" class="form-control" id="user" aria-describedby="user"
			placeholder="Enter username" />
	</div>

	<div class="form-group">
		<label for="email">Email</label>
		<input class="form-control" aria-describedby="email" id="email" type="email" name="email"
			placeholder="Enter email address" />
	</div>

	<div class="form-group">
		<label for="password">Password</label>
		<input type="password" name="password" id="password" placeholder="Enter password" class="form-control"
			aria-describedby="password" />
	</div>

	<div class="form-group">
		<label for="confirm_password">Confirm Password</label>
		<input type="password" name="confirm_password" placeholder="Confirm your password"
			aria-describedby="confirm_password" id="confirm_password" class="form-control" />
	</div>
	<button class="btn btn-primary">Sign Up</button>
</form>
<hr />
{% if error %}
{{ error }}
{% endif %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="todo app" />
    <meta name="keywords" content="todo app" />

    <title>Todo App</title>
    <link href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet"
        media="screen" />
    <script defer src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script defer src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>

<body>

    <header class="mb-4">
        <nav class="navbar navbar-dark bg-primary ">
            {% block nav %}
            <a class="navbar-brand text-light" href="{% url 'todo_app:index' %}">Home</a>
            {% endblock nav %}
            {% if user %}
            <a class="nav-link text-light" href="{% url 'todo_app:completed_todos' %}">Completed Todos</a>
            <a class="nav-link text-light" href="{% url 'login_app:delete_account' %}">Delete Account</a>
            <a class="nav-link text-light" href="{% url 'login_app:logout' %}">Log out</a>
            {% else%}
            <a class="nav-link text-light" href="{% url 'login_app:login' %}">Login</a>
            {% endif%}
        </nav>
    </header>

    <main class="container-md pb-5 mb-5">
        {% block main %}
        {% endblock main %}
    </main>
    <footer class="text-center text-white fixed-bottom bg-gradient-light bg-primary">
        <div class="text-center p-3">
            Kea-Todos!
        </div>
    </footer>
</body>

</html>

todo_app/templates/todo_app/completed_todos-copy.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<meta name="description" content="todo app" />
	<meta name="keywords" content="todo app" />
	<title>Completed Todos</title>
</head>

<body>
	<h1>Completed Todos</h1>
	<h2>Hello, {{ user }}</h2>
	<a href="{% url 'todo_app:index' %}">Todos</a>
	<a href="{% url 'login_app:logout' %}">Logout</a>
	<hr />
	<ul>
		{% for todo in todos  %}
		<li>
			<form action="{% url 'todo_app:change_status' %}" method="post">
				{% csrf_token %}
				<input type="checkbox" name="checked" {% if todo.status %}checked{% endif %} />
				<button>Update</button>
				<button formaction="{% url 'todo_app:delete_todo' %}">Delete</button>
				<input type="hidden" name="pk" value="{{ todo.pk }}" />
				{{ todo.text }}
			</form>
		</li>
		{% endfor  %}
	</ul>
	<hr />
	<a href="{% url 'todo_app:index' %}">Todos</a>
</body>

</html>

todo_app/templates/todo_app/completed_todos.html
{% extends 'base.html' %}

{% block main %}
<h1>Completed Todos</h1>
<hr />
<ul>
	{% for todo in todos  %}
	<li>
		<form action="{% url 'todo_app:change_status' %}" method="post">
			{% csrf_token %}
			<div>
				<input name="checked" type="checkbox" class="form-check-input" id="checked"
					{% if todo.status %}checked{% endif %} />
				<label class="font-weight-bold" for="checked">{{ todo.text }}</label>
			</div>
			<div class="ml-n4">
				<button class="btn btn-light ">Update</button>
				<button class="btn btn-secondary" formaction="{% url 'todo_app:delete_todo' %}">Delete</button>
				<input type="hidden" name="pk" value="{{ todo.pk }}" />
			</div>
		</form>
	</li>
	{% endfor  %}
</ul>
<hr />
<a href="{% url 'todo_app:index' %}">Todos</a>
{% endblock %}

todo_app/templates/todo_app/index-copy.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<meta name="description" content="todo app" />
	<meta name="keywords" content="todo app" />
	<title>Todo</title>
</head>

<body>
	<h1>Todo</h1>
	<h2>Hello, {{ user }}</h2>
	<a href="{% url 'todo_app:completed_todos' %}">Completed Todos</a>
	<a href="{% url 'login_app:logout' %}">Logout</a>
	<a href="{% url 'login_app:delete_account' %}">Delete account</a>
	<hr />
	<ul>
		{% for todo in todos  %}
		<li>
			<form action="{% url 'todo_app:change_status' %}" method="post">
				{% csrf_token %}
				<input type="checkbox" name="checked" {% if todo.status %}checked{% endif %} />
				<button>Update</button>
				<button formaction="{% url 'todo_app:delete_todo' %}">Delete</button>
				<input type="hidden" name="pk" value="{{ todo.pk }}" />
				{{ todo.text }}
			</form>
		</li>
		{% endfor  %}
	</ul>
	<hr />
	<form action="." method="post">
		{% csrf_token %}
		<input type="text" name="text" placeholder="Write your todo item here!" />
		<button>Create todo</button>
		<input type="hidden" name="pk" value="4" />
	</form>
	<a href="{% url 'todo_app:completed_todos' %}">Completed Todos</a>
</body>

</html>

todo_app/templates/todo_app/index.html
{% extends 'base.html' %}
{% block main %}
{% if user %}
<h6 class="mb-3">Welcome {{ userName }}</h6>
{% endif %}
<h1>Todos</h1>
<hr />

<ul>
	{% for todo in todos  %}
	<form action="{% url 'todo_app:change_status' %}" method="post">
		{% csrf_token %}
		<div>
			<input name="checked" type="checkbox" class="form-check-input" id="checked"
				{% if todo.status %}checked{% endif %} />
			<label class="font-weight-bold" for="checked">{{ todo.text }}</label>
		</div>
		<div class="ml-n4">
			<button class="btn btn-light ">Update</button>
			<button class="btn btn-secondary" formaction="{% url 'todo_app:delete_todo' %}">Delete</button>
			<input type="hidden" name="pk" value="{{ todo.pk }}" />
		</div>
	</form>
	<hr />
	{% endfor  %}
</ul>
<hr />

{% if user %}
<form action="." method="post">
	{% csrf_token %}
	<div class="form-group">
		<label for="todo">Add new todo</label>
		<input name="text" type="text" class="form-control" id="todo" aria-describedby="todo"
			placeholder="Write your todo here" />
	</div>

	<button class="btn btn-primary">Create todo</button>
	<a href="{% url 'todo_app:completed_todos' %}">Completed Todos</a>
	<input type="hidden" name="pk" value="4" />
</form>
{% else %}
<h3>Please login to view your Todos</h3>
<a class="btn btn-primary" href="{% url 'login_app:login' %}">Login</a>

{% endif %}
{% endblock %}